version: '3.8'
services:
  frontend:
    image: phawit/devtool-compose-front:1.0.0
    build: ./front-end
    ports:
      - "3000:80"
  backend:
    image: phawit/devtool-compose-back:1.0.0
    build: ./back-test/app
    ports:
      - "2000:3000"