version: '3.8'
services:
  front-end:
    image: phawit/devtool-front:1.0.0
    build: ./front-end
    ports:
      - "3100:80"
  backend:
    image: phawit/devtool-back:1.0.0
    build: ./back-test/app
    ports:
      - "3200:3000"
