pipeline {
    agent any
stages {
  
   stage('Pull code') {
       steps {
           checkout scm
       }
    }
    stage('Download dependency') {
       steps {
           dir('front-end') {
              echo 'npm install'
           }
       }
   }
    stage('Build') {
       steps {
           dir('front-end') {
              echo 'npm run build'
           }
       }
   }
    stage('Deployment') {
        steps{
                withCredentials([string(credentialsId: 'hostip', variable: 'ip'), string(credentialsId: 'username', variable: 'name'), string(credentialsId: 'password', variable: 'pass')]) {
                script {
                def remote = [:]
                remote.name = 'T09'
                remote.host = "${ip}"
                remote.user = "${name}"
                remote.password = "${pass}"
                remote.allowAnyHosts = true
                sshCommand remote: remote, command: "git clone https://github.com/phawit-s/ec2testdev.git"
                sshCommand remote: remote, command: "docker-compose -f ec2testdev/docker-compose.yml up -d"
                sshCommand remote: remote, command: "rm -r ec2testdev"
                    
                }
          
               }
        }       
      }
  
  }
}
